### ISSUE TITLE
startRecording Error of uninitialized AudioRecord Method

### ISSUE THREAD

**Issue by montaserfzy** [goodatlas/react-native-audio-record#14]
I am trying to create audio recorder on android i faced this error 

 `
  const options = {
            sampleRate: 16000,
            channels: 1,       
            bitsPerSample: 16,  
            audioSource: 6,    
            wavFile: 'test.wav' 
     }
`
`    AudioRecord.init(options);
     AudioRecord.start();
`

> React-native --v: 57.8 

![error](https://user-images.githubusercontent.com/8565425/52917500-f11b0680-32f4-11e9-9d96-f04dac929482.png)

**Comment by montaserfzy** [comment]
> I am trying to create audio recorder on android i faced this error
> 
> `const options = { sampleRate: 16000, channels: 1, bitsPerSample: 16, audioSource: 6, wavFile: 'test.wav' }; AudioRecord.init(options); AudioRecord.start();`
> 
> > React-native --v: 57.8
> 
> ![error](https://user-images.githubusercontent.com/8565425/52917500-f11b0680-32f4-11e9-9d96-f04dac929482.png)

**Comment by vinayr** [comment]
@montaserfzy you need to get microphone permission before `init`. Take a look at example app.

**Comment by raindev32** [comment]
face same issues with this..

any solutiosn for solve this thing ?

**Comment by fukemy** [comment]
```
  if(recorder.getState() != AudioRecord.STATE_INITIALIZED){
            return; //avoid crash
        }
```
