### ISSUE TITLE
file size 0 if bitPerSample is 8

### ISSUE THREAD

**Issue by diwu86** [goodatlas/react-native-audio-record#2]
Here are my options: 
  sampleRate: 11025, 
  channels: 1,      
  bitsPerSample: 8,  
  wavFile: 'test.wav'

After recording the test.wav size is 0. If I set bitsPerSample as 16, it works fine. Can anyone take a look at this issue? Thanks

**Comment by vinayr** [comment]
@diwu86 could you test with the latest version?
