### ISSUE TITLE
'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by teslavitas** [goodatlas/react-native-audio-record#26]
Hi,
After adding the package I am starting to get this error when build in Xcode.
When I try to build for iOS I am getting this error.
Has anyone faced it before?
<img width="383" alt="Screenshot 2019-09-11 at 10 33 50" src="https://user-images.githubusercontent.com/11631176/64677436-3749da00-d480-11e9-8d25-57c3095f2904.png">

**Comment by dan-lee** [comment]
Facing the same error with `react-native@0.61.0`. For what it's worth. It works with XCode but if I run `react-native run-ios` it doesn't. Very weird

**Comment by vamvoukas** [comment]
Create a react-native-audio-record.podspec file in your node_modules/react-native-audio-record with code below....and then pod install(react-native@0.61.0 has auto-linking)

`require 'json'
version = JSON.parse(File.read('package.json'))["version"]

Pod::Spec.new do |s|

  s.name            = "react-native-audio-record"
  s.version         = version
  s.homepage        = "https://github.com/goodatlas/react-native-audio-record"
  s.summary         = "Audio record buffers for iOS and Android."
  s.license         = "MIT"
  s.author          = "goodatlas"
  s.ios.deployment_target = '7.0'
  s.tvos.deployment_target = '9.0'
  s.source          = { :git => "https://github.com/goodatlas/react-native-audio-record.git", :tag => "v#{s.version}" }
  s.source_files    = 'ios/*.{h,m}'
  s.preserve_paths  = "**/*.js"
  s.frameworks = 'UIKit', 'Foundation'

  s.dependency 'React'

end`

**Comment by ekzotech** [comment]
I had the same issue too. Nor my project, nor clear new project.
[https://github.com/goodatlas/react-native-audio-record/issues/26#issuecomment-538347485](This) doesn't help me either.

**Comment by gaberoganlingumi** [comment]
I first experienced #27 because there was no podfile and then this issue after trying react-native link. I'm pretty sure you guys need to include a podfile in this library to make it work with modern versions of react. @vamvoukas comment is an inconvenient workaround but this needs to be in the project.

**Comment by ekzotech** [comment]
Tried again with brand new project.
react-native v. 0.61.2
react-native-audio-record v. 0.2.1
After installing the package I created podspec file, then ran 'pod install', everything was ok. Run iOS in simulator and got error 'native module cannot be null', tried to link the package and got the same.

**Comment by ekzotech** [comment]
UPDATE:
Just tried to use newest .podspec from latest commit (about 15 hours ago for the time of writing), and it WORKS! Thank you!

**Comment by is343** [comment]
Yes, this has been fixed with #16. 

Sorry for the delay on merging that PR. I've published the new version to npm.
