### ISSUE TITLE
Native Module cannot be null

### ISSUE THREAD

**Issue by AnanasPie** [goodatlas/react-native-audio-record#27]
Hi,

I get the following error when I try to import this library.
![Capture](https://user-images.githubusercontent.com/7532861/65260586-43ccd300-db0f-11e9-982b-62db5d2242c3.PNG)

**Comment by is343** [comment]
Did you link the library?

**Comment by gaberoganlingumi** [comment]
@is343 shouldn't have to in new react native versions, i think it's that it's missing a podspec

**Comment by is343** [comment]
The podspec file is now included. This should now be fixed with #16.
