### ISSUE TITLE
use with expo

### ISSUE THREAD

**Issue by flieks** [goodatlas/react-native-audio-record#29]
Can i use this with Expo ?
The native expo Audio API doesnt support streaming..

**Comment by is343** [comment]
No, not without ejecting. [expo docs](https://docs.expo.io/versions/latest/expokit/eject/)

**Comment by flieks** [comment]
Thanks but ejecting isnt a good option i think as we would lose alot of Expo's advantages, but i need this audio recording with buffer.
Too bad this `react-native link react-native-audio-record` needs to be done

**Comment by Davidzhu001** [comment]
any solution for expo users?

**Comment by dannycoulombe** [comment]
Having the same issue.

I am trying a workaround using `Expo Audio & FileSystem`. Based on the doc, `FileSystem.readAsStringAsync` accept both a position and a length, which I suppose could work if parsed with the buffer npm package. I'm working on this today.. if I manage to get it work, I'll create a npm package for expo and let you guys know.

**Comment by dannycoulombe** [comment]
OK... not going to work. Expo Audio writes to file every second more or less.. not enough to obtain a fluid waveform.
