### ISSUE TITLE
Set volume of recording

### ISSUE THREAD

**Issue by lingfeidiewu** [goodatlas/react-native-audio-record#6]
I use react-native-sound to play the sound recorded, the volume is too low. Is there any method to increase the volume?

**Comment by vinayr** [comment]
May be your device volume is low?
check sample app `App1.js` in Example folder.
Try react-native-sound methods like setCategory, setVolume.
Eg - `Sound.setCategory('Playback')`, `whoosh.setVolume(0.5)`

**Comment by saibharani** [comment]
i have submitted a pr to increase volume #11

**Comment by vinayr** [comment]
@saibharani thanks for the PR. Instead of a hardcoded audio source, I've made it as a configurable option. Check out the new release.
