### ISSUE TITLE
New Release Roadmap

### ISSUE THREAD

**Issue by mihikadutta** [goodatlas/react-native-audio-record#75]
Looking at the last release I got curious whether a new release is planned. Also, is it because there is a alternative project that is more actively developed?

**Comment by LunatiqueCoder** [comment]
@meherranjan I'm using [react-native-live-audio-stream](https://github.com/xiqi/react-native-live-audio-stream) but I also think that [react-native-audio-toolkit](https://github.com/react-native-audio-toolkit/react-native-audio-toolkit) can be a good choice.

**Comment by mihikadutta** [comment]
Thanks @criszz77, I am using your recommendation. 👍 🚀
