### ISSUE TITLE
Cannot resolve symbol goodatlas

### ISSUE THREAD

**Issue by alchibaucha** [goodatlas/react-native-audio-record#8]
After linking the package, this import statement cannot be resolved.

`import com.goodatlas.audiorecord.RNAudioRecordPackage`

package com.goodatlas.audiorecord does not exist

Cannot find symbol new RNAudioRecordPackage()

Thanks.

**Comment by lucasdutra13** [comment]
same issue here

**Comment by alchibaucha** [comment]
@lucasdutra13. For some reason, while linking the package, the package does not get added to the dependencies list on build.gradle(app) file.
To solve the problem, add 
`implementation project(':react-native-audio-record')`
in dependencies block.
It should properly work.
